Repository mocktools/go-smtp-mock, pull requests merged in 2021-12, with the labels that each got.

#42 Technical/Refactor functions/structures/constants scopes
  .circleci/config.yml
  .golangci.yml
  .tool-versions
  CHANGELOG.md
  README.md
  configuration.go
  configuration_test.go
  consts.go
  handler_data.go
  handler_data_test.go
  handler_helo.go
  handler_helo_test.go
  handler_mailfrom.go
  handler_mailfrom_test.go
  handler_message_test.go
  handler_quit.go
  handler_rcptto.go
  handler_rcptto_test.go
  helpers_test.go
  logger.go
  logger_test.go
  server.go
  server_test.go
  session.go
  session_test.go
  smtpmock.go
  smtpmock_test.go
  test_helpers_test.go
Labels: reviewed

#43 Golang smtpmock v0.1.2
  .circleci/config.yml
  .golangci.yml
  .tool-versions
  CHANGELOG.md
  README.md
  configuration.go
  configuration_test.go
  consts.go
  handler_data.go
  handler_data_test.go
  handler_helo.go
  handler_helo_test.go
  handler_mailfrom.go
  handler_mailfrom_test.go
  handler_message_test.go
  handler_quit.go
  handler_rcptto.go
  handler_rcptto_test.go
  helpers_test.go
  logger.go
  logger_test.go
  server.go
  server_test.go
  session.go
  session_test.go
  smtpmock.go
  smtpmock_test.go
  test_helpers_test.go
Labels: release

#44 Technical/Refactor ConfigurationAttr#assignDefaultValues method
  .golangci.yml
  configuration.go
  server.go
  smtpmock.go
Labels: reviewed

#45 Feature/Assigning random SMTP port by OS as default settings
  CHANGELOG.md
  README.md
  configuration.go
  configuration_test.go
  consts.go
  server.go
  server_test.go
  smtpmock_test.go
Labels: reviewed

#46 Golang smtpmock v1.0.0
  .golangci.yml
  CHANGELOG.md
  README.md
  configuration.go
  configuration_test.go
  consts.go
  server.go
  server_test.go
  smtpmock.go
  smtpmock_test.go
Labels: release

#47 Technical/Updated package docs
  README.md
Labels: reviewed

#48 Technical/Updated package docs (#47)
  README.md
Labels: documentation

#49 Bugfix/Change ConfigurationAttr unexported fields to exported fields
  CHANGELOG.md
  README.md
  configuration.go
  configuration_test.go
  handler_message_test.go
  server.go
  server_test.go
  smtpmock_test.go
Labels: reviewed

#50 Golang smtpmock v1.0.1
  CHANGELOG.md
  README.md
  configuration.go
  configuration_test.go
  handler_message_test.go
  server.go
  server_test.go
  smtpmock_test.go
Labels: release

#51 Feature/RFC compatibility for default negative SMTP command responses
  CHANGELOG.md
  configuration.go
  configuration_test.go
  consts.go
  handler_helo_test.go
  smtpmock_test.go
Labels: reviewed

#52 Golang smtpmock v1.1.0
  CHANGELOG.md
  configuration.go
  configuration_test.go
  consts.go
  handler_helo_test.go
  smtpmock_test.go
Labels: release

#55 Feature/Ability to use localhost as valid HELO domain
  CHANGELOG.md
  README.md
  consts.go
  handler_helo_test.go
Labels: reviewed

#58 Bugfix/Fix variables order in README.md
  README.md
Labels: reviewed

#59 Technical/Update github templates
  .github/PULL_REQUEST_TEMPLATE.md
Labels: reviewed

#60 Technical/Update package documentation, github templates
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: reviewed

#53 Feature/Ability to run smtpmock as service
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  README.md
  cmd/smtpmock.go
  cmd/smtpmock_test.go
  cmd/test_mocks_test.go
  configuration.go
  configuration_test.go
  handler_message.go
  handler_message_test.go
  smtpmock_test.go
Labels: reviewed

#62 Technical/Configure goreleaser
  .gitignore
  .goreleaser.yml
  CHANGELOG.md
  cmd/main.go
  cmd/main_test.go
Labels: reviewed

#63 Technical/Update CircleCI config
  .circleci/config.yml
  CHANGELOG.md
Labels: reviewed

#61 Golang smtpmock v1.3.5
  .circleci/config.yml
  .gitignore
  .goreleaser.yml
  CHANGELOG.md
  README.md
  cmd/main.go
  cmd/main_test.go
  cmd/test_mocks_test.go
  configuration.go
  configuration_test.go
  handler_message.go
  handler_message_test.go
  smtpmock_test.go
Labels: release

#64 Technical/Add security policy
  CHANGELOG.md
  SECURITY.md
Labels: reviewed

#65 Technical/Update github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: reviewed

#66 Feature/Ability to do server force stop by timeout
  CHANGELOG.md
  README.md
  SECURITY.md
  cmd/main.go
  cmd/main_test.go
  configuration.go
  configuration_test.go
  consts.go
  server.go
  server_test.go
Labels: reviewed

#67 Golang smtpmock v1.4.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/issue_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  SECURITY.md
  cmd/main.go
  cmd/main_test.go
  configuration.go
  configuration_test.go
  consts.go
  server.go
  server_test.go
Labels: release
